TAGS = [
    ("*special", "*особенный"),
    ("2-sat", "2-sat"),
    ("binary search", "бинарный поиск"),
    ("bitmasks", "битмаски"),
    ("brute force", "перебор"),
    ("chinese remainder theorem", "китайская теорема об остатках"),
    ("combinatorics", "комбинаторика"),
    ("constructive algorithms", "конструктивные алгоритмы"),
    ("data structures", "структуры данных"),
    ("dfs and similar", "поиск в глубину и подобное"),
    ("divide and conquer", "разделяй и властвуй"),
    ("dp", "дп"),
    ("dsu", "система непересекающихся множеств"),
    ("expression parsing", "разбор выражений"),
    ("fft", "Быстрое преобразование Фурье"),
    ("flows", "потоки"),
    ("games", "игры"),
    ("geometry", "геометрия"),
    ("graph matchings", "паросочетания"),
    ("graphs", "графы"),
    ("greedy", "жадные алгоритмы"),
    ("hashing", "хеши"),
    ("implementation", "реализация"),
    ("interactive", "интерактив"),
    ("math", "математика"),
    ("matrices", "матрицы"),
    ("meet-in-the-middle", "встреча посередине"),
    ("number theory", "теория чисел"),
    ("probabilities", "теория вероятностей"),
    ("schedules", "расписания"),
    ("shortest paths", "кратчайшие пути"),
    ("sortings", "сортировки"),
    ("string suffix structures", "строковые суфф. структуры"),
    ("strings", "строки"),
    ("ternary search", "тернарный поиск"),
    ("trees", "деревья"),
    ("two pointers", "два указателя"),
]
